name: Backend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Bun をセットアップ
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: 依存関係をインストール
        run: |
          bun install
          cd apps/backend
          bun install

      - name: ファイル構造を確認
        working-directory: apps/backend
        run: |
          echo "=== Backend directory structure ==="
          find . -type f -name "*.ts" | head -20
          echo "=== Checking errorHandler.ts ==="
          ls -la src/middlewares/errorHandler.ts || echo "errorHandler.ts not found"
          echo "=== Current directory ==="
          pwd

      - name: テストを実行
        working-directory: apps/backend
        run: bun test
